1. Import numpy as np and see the version

In [1]:
import numpy as np
np.__version__

'1.20.3'

2. How to create a 1D array?

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [6]:
boolea_arr = np.full((3,3), True, dtype=bool)

In [7]:
boolea_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [12]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

5. How to replace items that satisfy a condition with another value in numpy array?

In [13]:
arr[arr%2==1]=-1

In [14]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr[arr%2 == 0]=1

In [16]:
arr

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1])