1. Import numpy as np and see the version

In [1]:
import numpy as np
np.__version__

'1.20.3'

2. How to create a 1D array?

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [6]:
boolea_arr = np.full((3,3), True, dtype=bool)

In [7]:
boolea_arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

In [9]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [12]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

5. How to replace items that satisfy a condition with another value in numpy array?

In [13]:
arr[arr%2==1]=-1

In [14]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr[arr%2 == 0]=1

In [16]:
arr

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1])

How to replace items that satisfy a condition without affecting the original array

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
out = np.where(arr%2==1, -1, arr)

In [21]:
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7. How to reshape an array?


In [23]:
arr = np.arange(10)

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [29]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [30]:
np.concatenate([a,b], axis =0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

9. How to stack two arrays horizontally?


In [33]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [34]:
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [35]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])